<a href="https://colab.research.google.com/github/davro76/Data-Mining-Process/blob/main/ChurnResampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import libraries, read the dataset, and display the first observations of the dataset
import pandas as pd
filename = "https://raw.githubusercontent.com/fenago/datasets/main/churn.csv"
ChurnData = pd.read_csv(filename,sep=",")
ChurnData.head()

,churn,accountlength,internationalplan,voicemailplan,numbervmailmessages,totaldayminutes,totaldaycalls,totaldaycharge,totaleveminutes,totalevecalls,totalevecharge,totalnightminutes,totalnightcalls,totalnightcharge,totalintlminutes,totalintlcalls,totalintlcharge,numbercustomerservicecalls
0,No,128,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1
1,No,107,no,yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1
2,No,137,no,no,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0
3,No,84,yes,no,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2
4,No,75,yes,no,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3

In [3]:
# Getting column names
ChurnData.columns

Index(['churn', 'accountlength', 'internationalplan', 'voicemailplan',
       'numbervmailmessages', 'totaldayminutes', 'totaldaycalls',
       'totaldaycharge', 'totaleveminutes', 'totalevecalls', 'totalevecharge',
       'totalnightminutes', 'totalnightcalls', 'totalnightcharge',
       'totalintlminutes', 'totalintlcalls', 'totalintlcharge',
       'numbercustomerservicecalls'],
      dtype='object')

In [4]:
# Size of the Dataframe 
ChurnData.shape

(5000, 18)

In [5]:
# Treats the NUMERIC Cols
from sklearn.preprocessing import RobustScaler
rob_scaler = RobustScaler()

# Convert each of the cols to the scaled version
ChurnData['accountlengthScaled'] = rob_scaler.fit_transform(ChurnData['accountlength'].values.reshape(-1,1))
ChurnData['numbervmailmessagesScaled'] = rob_scaler.fit_transform(ChurnData['numbervmailmessages'].values.reshape(-1,1))
ChurnData['totaldayminutesScaled'] = rob_scaler.fit_transform(ChurnData['totaldayminutes'].values.reshape(-1,1))
ChurnData['totaldaychargeScaled'] = rob_scaler.fit_transform(ChurnData['totaldaycharge'].values.reshape(-1,1))
ChurnData['totaldaycallsScaled'] = rob_scaler.fit_transform(ChurnData['totaldaycalls'].values.reshape(-1,1))
ChurnData['totaleveminutesScaled'] = rob_scaler.fit_transform(ChurnData['totaleveminutes'].values.reshape(-1,1))
ChurnData['totalevecallsScaled'] = rob_scaler.fit_transform(ChurnData['totalevecalls'].values.reshape(-1,1))
ChurnData['totalevechargeScaled'] = rob_scaler.fit_transform(ChurnData['totalevecharge'].values.reshape(-1,1))
ChurnData['totalnightminutesScaled'] = rob_scaler.fit_transform(ChurnData['totalnightminutes'].values.reshape(-1,1))
ChurnData['totalnightcallsScaled'] = rob_scaler.fit_transform(ChurnData['totalnightcalls'].values.reshape(-1,1))
ChurnData['totalnightchargeScaled'] = rob_scaler.fit_transform(ChurnData['totalnightcharge'].values.reshape(-1,1))
ChurnData['totalintlminutesScaled'] = rob_scaler.fit_transform(ChurnData['totalintlminutes'].values.reshape(-1,1))
ChurnData['totalintlcallsScaled'] = rob_scaler.fit_transform(ChurnData['totalintlcalls'].values.reshape(-1,1))
ChurnData['totalintlchargeScaled'] = rob_scaler.fit_transform(ChurnData['totalintlcharge'].values.reshape(-1,1))
ChurnData['numbercustomerservicecallsScaled'] = rob_scaler.fit_transform(ChurnData['numbercustomerservicecalls'].values.reshape(-1,1))
# drop the original cols
ChurnData.drop(['accountlength','numbervmailmessages', 'totaldayminutes', 'totaldaycalls',
       'totaldaycharge', 'totaleveminutes', 'totalevecalls', 'totalevecharge',
       'totalnightminutes', 'totalnightcalls', 'totalnightcharge',
       'totalintlminutes', 'totalintlcalls', 'totalintlcharge',
       'numbercustomerservicecalls'],axis=1,inplace=True)

#print
ChurnData.head()

,churn,internationalplan,voicemailplan,accountlengthScaled,numbervmailmessagesScaled,totaldayminutesScaled,totaldaychargeScaled,totaldaycallsScaled,totaleveminutesScaled,totalevecallsScaled,totalevechargeScaled,totalnightminutesScaled,totalnightcallsScaled,totalnightchargeScaled,totalintlminutesScaled,totalintlcallsScaled,totalintlchargeScaled,numbercustomerservicecallsScaled
0,No,no,yes,0.518519,1.470588,1.172414,1.172890,0.384615,-0.053156,-0.037037,-0.053819,0.653392,-0.346154,0.652459,-0.085714,-0.333333,-0.085106,0.0
1,No,no,yes,0.129630,1.529412,-0.255172,-0.255682,0.884615,-0.081211,0.111111,-0.081597,0.796460,0.115385,0.796721,0.971429,-0.333333,0.978723,0.0
2,No,no,no,0.685185,0.000000,0.873103,0.873377,0.538462,-1.178295,0.370370,-1.178819,-0.557522,0.153846,-0.557377,0.542857,0.333333,0.542553,-1.0
3,No,yes,no,-0.296296,0.000000,1.645517,1.646104,-1.115385,-2.053894,-0.444444,-2.053819,-0.051622,-0.423077,-0.052459,-1.057143,1.000000,-1.063830,1.0
4,No,yes,no,-0.462963,0.000000,-0.184828,-0.185065,0.500000,-0.778147,0.814815,-0.777778,-0.199115,0.807692,-0.200000,-0.057143,-0.333333,-0.053191,2.0

In [6]:
# TREAT THE CAT cols (encoding)
ChurnDataCat = pd.get_dummies(ChurnData[['internationalplan','voicemailplan']])

In [7]:
ChurnDataCat.head()

,internationalplan_no,internationalplan_yes,voicemailplan_no,voicemailplan_yes
0,1,0,0,1
1,1,0,0,1
2,1,0,1,0
3,0,1,1,0
4,0,1,1,0

In [8]:
# Getting column names
ChurnData.columns

Index(['churn', 'internationalplan', 'voicemailplan', 'accountlengthScaled',
       'numbervmailmessagesScaled', 'totaldayminutesScaled',
       'totaldaychargeScaled', 'totaldaycallsScaled', 'totaleveminutesScaled',
       'totalevecallsScaled', 'totalevechargeScaled',
       'totalnightminutesScaled', 'totalnightcallsScaled',
       'totalnightchargeScaled', 'totalintlminutesScaled',
       'totalintlcallsScaled', 'totalintlchargeScaled',
       'numbercustomerservicecallsScaled'],
      dtype='object')

In [9]:
# Seperating the numerical data
ChurnDataNum = ChurnData [['accountlengthScaled',
       'numbervmailmessagesScaled', 'totaldayminutesScaled',
       'totaldaychargeScaled', 'totaldaycallsScaled', 'totaleveminutesScaled',
       'totalevecallsScaled', 'totalevechargeScaled',
       'totalnightminutesScaled', 'totalnightcallsScaled',
       'totalnightchargeScaled', 'totalintlminutesScaled',
       'totalintlcallsScaled', 'totalintlchargeScaled',
       'numbercustomerservicecallsScaled']]
ChurnDataNum.shape

(5000, 15)

In [10]:
# Merging with the original data frame
# Preparing the X variables
X = pd.concat([ChurnDataCat, ChurnDataNum], axis=1)
print(X.shape)
# Preparing the Y variable
Y = ChurnData['churn']
print(Y.shape)
X.head()

(5000, 19)
(5000,)

,internationalplan_no,internationalplan_yes,voicemailplan_no,voicemailplan_yes,accountlengthScaled,numbervmailmessagesScaled,totaldayminutesScaled,totaldaychargeScaled,totaldaycallsScaled,totaleveminutesScaled,totalevecallsScaled,totalevechargeScaled,totalnightminutesScaled,totalnightcallsScaled,totalnightchargeScaled,totalintlminutesScaled,totalintlcallsScaled,totalintlchargeScaled,numbercustomerservicecallsScaled
0,1,0,0,1,0.518519,1.470588,1.172414,1.172890,0.384615,-0.053156,-0.037037,-0.053819,0.653392,-0.346154,0.652459,-0.085714,-0.333333,-0.085106,0.0
1,1,0,0,1,0.129630,1.529412,-0.255172,-0.255682,0.884615,-0.081211,0.111111,-0.081597,0.796460,0.115385,0.796721,0.971429,-0.333333,0.978723,0.0
2,1,0,1,0,0.685185,0.000000,0.873103,0.873377,0.538462,-1.178295,0.370370,-1.178819,-0.557522,0.153846,-0.557377,0.542857,0.333333,0.542553,-1.0
3,0,1,1,0,-0.296296,0.000000,1.645517,1.646104,-1.115385,-2.053894,-0.444444,-2.053819,-0.051622,-0.423077,-0.052459,-1.057143,1.000000,-1.063830,1.0
4,0,1,1,0,-0.462963,0.000000,-0.184828,-0.185065,0.500000,-0.778147,0.814815,-0.777778,-0.199115,0.807692,-0.200000,-0.057143,-0.333333,-0.053191,2.0

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=123,stratify=Y)
# Defining the LogisticRegression function
ChurnDataModel = LogisticRegression()
ChurnDataModel.fit(X_train, y_train)

LogisticRegression()

In [12]:
ChurnDataModel = LogisticRegression(max_iter=1000)
ChurnDataModel.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [13]:
pred = ChurnDataModel.predict(X_test)
print('Accuracy of Logistic regression model prediction on test set: {:.2f}'.format(ChurnDataModel.score(X_test, y_test)))

# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

Accuracy of Logistic regression model prediction on test set: 0.86
[[1250   38]
 [ 170   42]]
              precision    recall  f1-score   support

          No       0.88      0.97      0.92      1288
         Yes       0.53      0.20      0.29       212

    accuracy                           0.86      1500
   macro avg       0.70      0.58      0.61      1500
weighted avg       0.83      0.86      0.83      1500

In [14]:
print('Percentage of positive class :',(y_train[y_train=='Yes'].value_counts()/len(y_train) ) * 100)
print('Percentage of negative class :',(y_train[y_train=='No'].value_counts()/len(y_train) ) * 100)

Percentage of positive class : Yes    14.142857
Name: churn, dtype: float64
Percentage of negative class : No    85.857143
Name: churn, dtype: float64

# Undersample

In [15]:
from sklearn.model_selection import train_test_split

# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=123,stratify=Y)

In [16]:
# let us first join the train_x and train_y for ease of operation

trainData = pd.concat([X_train,y_train],axis=1)
trainData.head()

,internationalplan_no,internationalplan_yes,voicemailplan_no,voicemailplan_yes,accountlengthScaled,numbervmailmessagesScaled,totaldayminutesScaled,totaldaychargeScaled,totaldaycallsScaled,totaleveminutesScaled,totalevecallsScaled,totalevechargeScaled,totalnightminutesScaled,totalnightcallsScaled,totalnightchargeScaled,totalintlminutesScaled,totalintlcallsScaled,totalintlchargeScaled,numbercustomerservicecallsScaled,churn
2326,1,0,1,0,0.444444,0.0,1.012414,1.012987,0.153846,-1.227021,0.851852,-1.227431,0.709440,0.153846,0.708197,1.057143,-0.666667,1.063830,-1.0,No
2013,1,0,1,0,-0.148148,0.0,0.226207,0.226461,-0.692308,-0.162422,-0.407407,-0.163194,-0.548673,-0.038462,-0.550820,0.142857,-0.666667,0.148936,1.0,No
3671,1,0,1,0,0.759259,0.0,-0.577931,-0.578734,-0.230769,-0.363234,-0.592593,-0.364583,-0.258112,0.384615,-0.259016,0.228571,0.666667,0.234043,2.0,No
238,1,0,1,0,2.129630,0.0,-1.331034,-1.331981,1.846154,-1.182724,-0.333333,-1.182292,0.386431,0.384615,0.386885,0.114286,1.666667,0.117021,-1.0,No
66,0,1,1,0,-1.055556,0.0,0.984828,0.985390,0.192308,0.174234,0.148148,0.173611,-0.628319,-1.269231,-0.629508,-0.285714,0.000000,-0.287234,-1.0,No

In [17]:
# Finding the indexes of the sample data set where the propensity is 'yes'
ind = trainData[trainData['churn']=='Yes'].index
print(len(ind))

# Seperate the minority classes
minData = trainData.loc[ind]
print(minData.shape)

# Finding indexes of majority class
ind1 = trainData[trainData['churn']=='No'].index
print(len(ind1))
# Seperating the majority class
majData = trainData.loc[ind1]
print(majData.shape)
majData.head()

495
(495, 20)
3005
(3005, 20)

,internationalplan_no,internationalplan_yes,voicemailplan_no,voicemailplan_yes,accountlengthScaled,numbervmailmessagesScaled,totaldayminutesScaled,totaldaychargeScaled,totaldaycallsScaled,totaleveminutesScaled,totalevecallsScaled,totalevechargeScaled,totalnightminutesScaled,totalnightcallsScaled,totalnightchargeScaled,totalintlminutesScaled,totalintlcallsScaled,totalintlchargeScaled,numbercustomerservicecallsScaled,churn
2326,1,0,1,0,0.444444,0.0,1.012414,1.012987,0.153846,-1.227021,0.851852,-1.227431,0.709440,0.153846,0.708197,1.057143,-0.666667,1.063830,-1.0,No
2013,1,0,1,0,-0.148148,0.0,0.226207,0.226461,-0.692308,-0.162422,-0.407407,-0.163194,-0.548673,-0.038462,-0.550820,0.142857,-0.666667,0.148936,1.0,No
3671,1,0,1,0,0.759259,0.0,-0.577931,-0.578734,-0.230769,-0.363234,-0.592593,-0.364583,-0.258112,0.384615,-0.259016,0.228571,0.666667,0.234043,2.0,No
238,1,0,1,0,2.129630,0.0,-1.331034,-1.331981,1.846154,-1.182724,-0.333333,-1.182292,0.386431,0.384615,0.386885,0.114286,1.666667,0.117021,-1.0,No
66,0,1,1,0,-1.055556,0.0,0.984828,0.985390,0.192308,0.174234,0.148148,0.173611,-0.628319,-1.269231,-0.629508,-0.285714,0.000000,-0.287234,-1.0,No

In [18]:
# Take a random sample equal to length of the minority class to make the data set balanced

majSample = majData.sample(n=len(ind),random_state = 123)
print(majSample.shape)
majSample.head()

(495, 20)

,internationalplan_no,internationalplan_yes,voicemailplan_no,voicemailplan_yes,accountlengthScaled,numbervmailmessagesScaled,totaldayminutesScaled,totaldaychargeScaled,totaldaycallsScaled,totaleveminutesScaled,totalevecallsScaled,totalevechargeScaled,totalnightminutesScaled,totalnightcallsScaled,totalnightchargeScaled,totalintlminutesScaled,totalintlcallsScaled,totalintlchargeScaled,numbercustomerservicecallsScaled,churn
3214,0,1,1,0,0.907407,0.000000,0.011034,0.010552,-0.807692,-0.090070,-0.629630,-0.090278,-0.038348,0.346154,-0.039344,-0.428571,1.666667,-0.425532,2.0,No
886,1,0,0,1,0.055556,1.823529,-0.998621,-0.999188,0.923077,-0.178664,0.148148,-0.178819,-0.061947,-0.076923,-0.062295,-0.400000,-0.333333,-0.404255,-1.0,No
2927,1,0,0,1,0.462963,1.352941,-0.822069,-0.822240,0.153846,0.395718,0.555556,0.394097,-0.617994,0.000000,-0.619672,-0.028571,-0.333333,-0.031915,0.0,No
3603,1,0,1,0,-0.407407,0.000000,-0.553103,-0.553571,-0.615385,0.233296,-1.000000,0.232639,0.355457,0.076923,0.354098,-0.371429,0.666667,-0.372340,1.0,No
621,1,0,1,0,0.481481,0.000000,-0.795862,-0.796266,-0.461538,-0.844592,0.407407,-0.845486,-0.640118,0.230769,-0.639344,0.342857,-0.333333,0.351064,0.0,No

In [19]:
# Concatinating both data sets and then shuffling the data set

balData = pd.concat([minData,majSample],axis = 0)
print('balanced data set shape',balData.shape)

# Shuffling the data set

from sklearn.utils import shuffle

balData = shuffle(balData)
balData.head()

balanced data set shape (990, 20)

,internationalplan_no,internationalplan_yes,voicemailplan_no,voicemailplan_yes,accountlengthScaled,numbervmailmessagesScaled,totaldayminutesScaled,totaldaychargeScaled,totaldaycallsScaled,totaleveminutesScaled,totalevecallsScaled,totalevechargeScaled,totalnightminutesScaled,totalnightcallsScaled,totalnightchargeScaled,totalintlminutesScaled,totalintlcallsScaled,totalintlchargeScaled,numbercustomerservicecallsScaled,churn
4309,0,1,1,0,0.148148,0.0,-0.590345,-0.590909,-1.230769,-0.844592,-0.222222,-0.845486,0.564897,0.038462,0.563934,-0.400000,-1.000000,-0.404255,0.0,Yes
2159,1,0,1,0,0.592593,0.0,0.137931,0.137987,0.192308,-0.277593,0.592593,-0.277778,1.171091,0.192308,1.170492,0.771429,-0.666667,0.776596,0.0,No
4943,1,0,1,0,0.592593,0.0,1.182069,1.182630,0.846154,1.241787,-0.370370,1.239583,-0.247788,0.923077,-0.249180,0.942857,1.666667,0.946809,1.0,Yes
679,0,1,1,0,-0.462963,0.0,0.583448,0.583604,-0.846154,1.860465,0.407407,1.859375,0.112094,0.153846,0.111475,-0.457143,1.666667,-0.457447,0.0,Yes
2816,1,0,1,0,0.555556,0.0,1.153103,1.153409,0.500000,-0.214101,0.111111,-0.215278,-0.075221,-0.038462,-0.075410,2.285714,0.666667,2.297872,0.0,Yes

In [22]:
balData.shape

(990, 20)

In [26]:
# Making the new X_train and y_train

X_trainNew = balData.iloc[:,0:19]
X_trainNew.head()

y_trainNew = balData['churn']
y_trainNew.head()

4309    Yes
2159     No
4943    Yes
679     Yes
2816    Yes
Name: churn, dtype: object

In [27]:
# Defining the LogisticRegression function
ChurnModel1 = LogisticRegression(max_iter=1000)
ChurnModel1.fit(X_trainNew, y_trainNew)

# Predicting on the test
pred = ChurnModel1.predict(X_test)
print('Accuracy of Logisticr regression model prediction on test set for balanced data set: {:.2f}'.format(ChurnModel1.score(X_test, y_test)))

Accuracy of Logisticr regression model prediction on test set for balanced data set: 0.76

In [28]:
# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

[[978 310]
 [ 47 165]]

In [29]:
# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

[[978 310]
 [ 47 165]]
              precision    recall  f1-score   support

          No       0.95      0.76      0.85      1288
         Yes       0.35      0.78      0.48       212

    accuracy                           0.76      1500
   macro avg       0.65      0.77      0.66      1500
weighted avg       0.87      0.76      0.79      1500

# Oversampling

In [30]:
!pip install smote-variants

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting smote-variants
  Downloading smote_variants-0.7.1-py3-none-any.whl (407 kB)
     |████████████████████████████████| 407 kB 4.9 MB/s
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from smote-variants) (1.7.3)
Collecting statistics
  Downloading statistics-1.0.3.5.tar.gz (8.3 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.8/dist-packages (from smote-variants) (2.9.0)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.8/dist-packages (from smote-variants) (2.9.2)
Requirement already satisfied: mkl in /usr/local/lib/python3.8/dist-packages (from smote-variants) (2019.0)
Requirement already satisfied: numpy>=1.13.0 in /usr/local/lib/python3.8/dist-packages (from smote-variants) (1.21.6)
Collecting metric-learn
  Downloading metric_learn-0.6.2-py2.py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 3.0 MB/s
Collecting minisom
  Downloading MiniSom-2.3.0.tar.gz (8.8 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.8/dist-packages (from smote-variants) (1.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from smote-variants) (1.3.5)
Requirement already satisfied: seaborn in /usr/local/lib/python3.8/dist-packages (from smote-variants) (0.11.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from smote-variants) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->smote-variants) (3.1.0)
Requirement already satisfied: intel-openmp in /usr/local/lib/python3.8/dist-packages (from mkl->smote-variants) (2022.2.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->smote-variants) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->smote-variants) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas->smote-variants) (1.15.0)
Requirement already satisfied: matplotlib>=2.2 in /usr/local/lib/python3.8/dist-packages (from seaborn->smote-variants) (3.2.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->seaborn->smote-variants) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->seaborn->smote-variants) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->seaborn->smote-variants) (0.11.0)
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python3.8/dist-packages (from statistics->smote-variants) (0.17.1)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (2.1.1)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (0.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (4.1.1)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (3.1.0)
Requirement already satisfied: tensorboard<2.10,>=2.9 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (2.9.1)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (14.0.6)
Requirement already satisfied: flatbuffers<2,>=1.12 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (1.12)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (1.3.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (1.14.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (21.3)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (1.1.2)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (3.19.6)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (1.6.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (1.50.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (3.3.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (0.28.0)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (2.9.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from tensorflow->smote-variants) (57.4.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.8/dist-packages (from astunparse>=1.6.0->tensorflow->smote-variants) (0.38.4)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->smote-variants) (0.6.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->smote-variants) (1.0.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->smote-variants) (2.14.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->smote-variants) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->smote-variants) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->smote-variants) (2.23.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->smote-variants) (0.4.6)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (4.13.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (3.10.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (2022.9.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (2.10)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow->smote-variants) (3.2.2)
Building wheels for collected packages: minisom, statistics
  Building wheel for minisom (setup.py) ... done
  Created wheel for minisom: filename=MiniSom-2.3.0-py3-none-any.whl size=9016 sha256=1fe53735b67a62a5b5f21f79e4449dde54d3ccc9d88f046d36f735ea55fed428
  Stored in directory: /root/.cache/pip/wheels/6d/4e/9e/a95c14a232a196c22d9c04b221ff5d25461a1a4c55339c61db
  Building wheel for statistics (setup.py) ... done
  Created wheel for statistics: filename=statistics-1.0.3.5-py3-none-any.whl size=7453 sha256=2692883219689db4b13416e657c20eba3a654fb18dfcf617c1377eb5bbececa6
  Stored in directory: /root/.cache/pip/wheels/36/4b/c7/6af97584669b756c0d60c5ff05d5fb1f533a4e4d96e5ee92b9
Successfully built minisom statistics
Installing collected packages: statistics, minisom, metric-learn, smote-variants
Successfully installed metric-learn-0.6.2 minisom-2.3.0 smote-variants-0.7.1 statistics-1.0.3.5

In [31]:
# Splitting the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0, stratify=Y)

print("Before OverSampling count of yes: {}".format(sum(y_train=='Yes')))
print("Before OverSampling count of no: {} \n".format(sum(y_train=='No')))

Before OverSampling count of yes: 495
Before OverSampling count of no: 3005

In [33]:
import smote_variants as sv
import numpy as np

# Instantiating the SMOTE class
oversampler= sv.SMOTE()

# Creating new training set

X_train_us, y_train_us = oversampler.sample(np.array(X_train), np.array(y_train))

# Shape after oversampling

print('After OverSampling, the shape of train_X: {}'.format(X_train_us.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_us.shape))

print("After OverSampling, counts of label 'Yes': {}".format(sum(y_train_us=='Yes')))
print("After OverSampling, counts of label 'no': {}".format(sum(y_train_us=='No')))

2022-12-01 16:26:01,078:INFO:SMOTE: Running sampling via ('SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 2, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': None, 'class_name': 'SMOTE'}")
INFO:smote_variants:SMOTE: Running sampling via ('SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'ss_params': {'n_dim': 2, 'simplex_sampling': 'random', 'within_simplex_sampling': 'random', 'gaussian_component': {}}, 'random_state': None, 'class_name': 'SMOTE'}")
2022-12-01 16:26:01,090:INFO:NearestNeighborsWithMetricTensor: NN fitting with metric minkowski
INFO:smote_variants:NearestNeighborsWithMetricTensor: NN fitting with metric minkowski
2022-12-01 16:26:01,096:INFO:NearestNeighborsWithMetricTensor: kneighbors query minkowski
INFO:smote_variants:NearestNeighborsWithMetricTensor: kneighbors query minkowski
2022-12-01 16:26:01,111:INFO:SMOTE: simplex sampling with n_dim 2
INFO:smote_variants:SMOTE: simplex sampling with n_dim 2

After OverSampling, the shape of train_X: (6010, 19)
After OverSampling, the shape of train_y: (6010,)

After OverSampling, counts of label 'Yes': 3005
After OverSampling, counts of label 'no': 3005

In [34]:
# Training the model with Logistic regression model

# Defining the LogisticRegression function

ChurnModel2 = LogisticRegression(max_iter=1000)

ChurnModel2.fit(X_train_us, y_train_us)

# Predicting on the test set
pred = ChurnModel2.predict(X_test)

# Printing accuracy 
print('Accuracy of Logistic regression model prediction on test set for Smote balanced data set: {:.2f}'.format(ChurnModel2.score(X_test, y_test)))

# Confusion Matrix for the model

from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

# Classification report for the model

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

Accuracy of Logistic regression model prediction on test set for Smote balanced data set: 0.76
[[988 300]
 [ 53 159]]
              precision    recall  f1-score   support

          No       0.95      0.77      0.85      1288
         Yes       0.35      0.75      0.47       212

    accuracy                           0.76      1500
   macro avg       0.65      0.76      0.66      1500
weighted avg       0.86      0.76      0.80      1500

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [35]:
import smote_variants as sv
import numpy as np
# Instantiating the SMOTE class
oversampler= sv.MSMOTE()
# Creating new training sts
X_train_us, y_train_us = oversampler.sample(np.array(X_train), np.array(y_train))

# Shape after oversampling
print('After OverSampling, the shape of train_X: {}'.format(X_train_us.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_us.shape))

print("After OverSampling, counts of label 'Yes': {}".format(sum(y_train_us=='Yes')))
print("After OverSampling, counts of label 'no': {}".format(sum(y_train_us=='No')))

2022-12-01 16:29:21,882:INFO:MSMOTE: Running sampling via ('MSMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'random_state': None, 'class_name': 'MSMOTE'}")
INFO:smote_variants:MSMOTE: Running sampling via ('MSMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'random_state': None, 'class_name': 'MSMOTE'}")
2022-12-01 16:29:21,890:INFO:NearestNeighborsWithMetricTensor: NN fitting with metric minkowski
INFO:smote_variants:NearestNeighborsWithMetricTensor: NN fitting with metric minkowski
2022-12-01 16:29:21,897:INFO:NearestNeighborsWithMetricTensor: kneighbors query minkowski
INFO:smote_variants:NearestNeighborsWithMetricTensor: kneighbors query minkowski

After OverSampling, the shape of train_X: (6010, 19)
After OverSampling, the shape of train_y: (6010,)

After OverSampling, counts of label 'Yes': 3005
After OverSampling, counts of label 'no': 3005

In [36]:
# Fitting model

# Training the model with Logistic regression model

# Defining the LogisticRegression function
ChurnModel2 = LogisticRegression(max_iter=1000)
ChurnModel2.fit(X_train_us, y_train_us)

# Predicting on the test
pred = ChurnModel2.predict(X_test)
print('Accuracy of Logistic regression model prediction on test set for Smote balanced data set: {:.2f}'.format(ChurnModel2.score(X_test, y_test)))

# Confusion Matrix for the model
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, pred)
print(confusionMatrix)

from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

Accuracy of Logistic regression model prediction on test set for Smote balanced data set: 0.77
[[1005  283]
 [  56  156]]
              precision    recall  f1-score   support

          No       0.95      0.78      0.86      1288
         Yes       0.36      0.74      0.48       212

    accuracy                           0.77      1500
   macro avg       0.65      0.76      0.67      1500
weighted avg       0.86      0.77      0.80      1500

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(